## Activity
Search for a weather API. Get data from the last seven days. You must include:

- Temperature
- Rain (mm)

Save the data in a **CSV file**.

In [3]:
import requests as rq
import pandas as pd
from datetime import datetime, timedelta


# Method to make daily frame
def makeTable(timeData, targetCity):
    # Daily means last 7 days
    daily = timeData['daily']
    df = pd.DataFrame({
        "city": targetCity,
        "day": daily['time'],
        "temp_max": daily['temperature_2m_max'],
        "rain": daily['precipitation_sum'],
        "wind": daily['windspeed_10m_max']
    })
    # Add column of fahrenheit
    df["temp_fahrenheit"] = df["temp_max"] * 9/5 + 32
    df.to_csv("tableDaily.csv", index=False)

# Method to print table
def printTable():
  df = pd.read_csv("tableDaily.csv")
  display(df)

# Varible to guard lat and lon of insert citys
# Start with: Campinas, Indaiatuba and Hortolândia
coordinates = [
    (-22.9056, -47.0608),
    (-23.0900, -47.2178),
    (-22.85833, -47.22000),
]

# Today
end_date = datetime.today()
start_date = end_date - timedelta(days=7)
# format to string (API format)
end_date_str = end_date.strftime("%Y-%m-%d")
start_date_str = start_date.strftime("%Y-%m-%d")

while True:
  print("====== Daily city's weather ======")
  lat = float(input('Type your latitude: '))
  lon = float(input('Type your longitude: '))
  coordinates.append((lat, lon))

  op = input("Do you wanna get information of another city? (Y/N)\n> ").upper()
  if op != 'Y':
    break
  else:
    continue

# Target url for request
url_weather = 'https://api.open-meteo.com/v1/forecast'

# Get nominatim API
url_location = "https://nominatim.openstreetmap.org/reverse"

# Header required by Nominatim API for requests
headers = {
    "User-Agent": "meu_app_teste"
}

# Results for request
dfs = []

for lat, lon in coordinates:
  # Parameters sent to the API request Weather
  params = {
      # Geographic coordinates for API request
      "latitude": lat,
      "longitude": lon,
      # Daily weather variables returned by API
      "daily": "temperature_2m_max,precipitation_sum,windspeed_10m_max",
      "start_date": start_date_str,
      "end_date": end_date_str,
      "timezone": "auto"
  }
  # Parameters sent to the API request Location
  param_geo = {
    "lat": lat,
    "lon": lon,
    "format": "json"
  }
  # Send request to the API weather with the parameters
  response_weather = rq.get(url_weather, params=params)
  # Send request to the API location with the parameters
  response_location = rq.get(url_location, params=param_geo, headers=headers)
  if response_weather.status_code == 200 and response_location.status_code == 200:
    # Data for weather and location
    data_weather = response_weather.json()
    data_location = response_location.json()

    #Variable to get target city in API retunr in a object
    endereco = data_location.get("address", {})

    # Get the target city in object
    city = endereco.get("city") or endereco.get("town") or endereco.get("village")

    # Make table with weather and the target city
    df = makeTable(data_weather, city)
    dfs.append(df)

    # Show Table with all citys on:
    printTable()

  else:
    print("API ERROR...")

====== Daily city's weather ======
Type your latitude: -22.9703
Type your longitude: -46.9978
Do you wanna get information of another city? (Y/N)
> n

       city         day  temp_max  rain  wind  temp_fahrenheit
0  Campinas  2026-04-09      27.8   2.9  16.2            82.04
1  Campinas  2026-04-10      25.6   1.5  15.0            78.08
2  Campinas  2026-04-11      27.0   0.0  19.3            80.60
3  Campinas  2026-04-12      28.3   0.0  15.6            82.94
4  Campinas  2026-04-13      28.0   0.0   8.9            82.40
5  Campinas  2026-04-14      28.1   0.0  15.4            82.58
6  Campinas  2026-04-15      28.3   0.0  14.9            82.94
7  Campinas  2026-04-16      28.6   0.0  10.0            83.48

         city         day  temp_max  rain  wind  temp_fahrenheit
0  Indaiatuba  2026-04-09      27.7   4.6  15.0            81.86
1  Indaiatuba  2026-04-10      24.9   0.0  13.3            76.82
2  Indaiatuba  2026-04-11      27.5   0.0  14.3            81.50
3  Indaiatuba  2026-04-12      28.5   0.0  10.0            83.30
4  Indaiatuba  2026-04-13      28.0   0.0   7.9            82.40
5  Indaiatuba  2026-04-14      28.3   0.0  13.8            82.94
6  Indaiatuba  2026-04-15      28.9   0.0   9.2            84.02
7  Indaiatuba  2026-04-16      29.0   0.0   6.1            84.20

          city         day  temp_max  rain  wind  temp_fahrenheit
0  Hortolândia  2026-04-09      28.5   3.4  12.0            83.30
1  Hortolândia  2026-04-10      25.6   0.4  14.4            78.08
2  Hortolândia  2026-04-11      27.4   0.0  12.8            81.32
3  Hortolândia  2026-04-12      28.3   0.0  10.3            82.94
4  Hortolândia  2026-04-13      27.8   0.0   7.0            82.04
5  Hortolândia  2026-04-14      27.9   0.0   9.0            82.22
6  Hortolândia  2026-04-15      28.0   0.0   8.9            82.40
7  Hortolândia  2026-04-16      28.5   0.0   6.6            83.30

       city         day  temp_max  rain  wind  temp_fahrenheit
0  Valinhos  2026-04-09      28.4   3.3  15.9            83.12
1  Valinhos  2026-04-10      25.9   1.0  15.4            78.62
2  Valinhos  2026-04-11      27.7   0.0  18.4            81.86
3  Valinhos  2026-04-12      29.1   0.0  16.1            84.38
4  Valinhos  2026-04-13      28.6   0.0   9.4            83.48
5  Valinhos  2026-04-14      28.6   0.0  14.0            83.48
6  Valinhos  2026-04-15      28.9   0.0  14.0            84.02
7  Valinhos  2026-04-16      29.4   0.0  10.5            84.92