## Activity
Search for a weather API. Get data from the last seven days. You must include:

- Temperature
- Rain (mm)

Save the data in a **CSV file**.

In [54]:
import requests as rq
import pandas as pd
from datetime import datetime, timedelta


# Method to make daily frame
def makeTable(timeData, targetCity):
    # Daily means last 7 days
    daily = timeData['daily']
    df = pd.DataFrame({
        "city": targetCity,
        "day": daily['time'],
        "temp_max": daily['temperature_2m_max'],
        "rain": daily['precipitation_sum'],
        "wind": daily['windspeed_10m_max']
    })
    df.to_csv("tableDaily.csv", index=False)

# Method to print table
def printTable():
  df = pd.read_csv("tableDaily.csv")
  display(df)

# Varible to guard lat and lon of insert citys
# Start with: Campinas, Indaiatuba and Hortolândia
coordinates = [
    (-22.9056, -47.0608),
    (-23.0900, -47.2178),
    (-22.85833, -47.22000),
]

# Today
end_date = datetime.today()
start_date = end_date - timedelta(days=7)
# format to string (API format)
end_date_str = end_date.strftime("%Y-%m-%d")
start_date_str = start_date.strftime("%Y-%m-%d")

while True:
  print("====== Daily city's weather ======")
  lat = float(input('Type your latitude: '))
  lon = float(input('Type your longitude: '))
  coordinates.append((lat, lon))

  op = input("Do you wanna get information of another city? (Y/N)\n> ").upper()
  if op != 'Y':
    break
  else:
    continue

# Target url for request
url_weather = 'https://api.open-meteo.com/v1/forecast'

# Get nominatim API
url_location = "https://nominatim.openstreetmap.org/reverse"

# Header required by Nominatim API for requests
headers = {
    "User-Agent": "meu_app_teste"
}

# Results for request
dfs = []

for lat, lon in coordinates:
  # Parameters sent to the API request Weather
  params = {
      # Geographic coordinates for API request
      "latitude": lat,
      "longitude": lon,
      # Daily weather variables returned by API
      "daily": "temperature_2m_max,precipitation_sum,windspeed_10m_max",
      "start_date": start_date_str,
      "end_date": end_date_str,
      "timezone": "auto"
  }
  # Parameters sent to the API request Location
  param_geo = {
    "lat": lat,
    "lon": lon,
    "format": "json"
  }
  # Send request to the API weather with the parameters
  response_weather = rq.get(url_weather, params=params)
  # Send request to the API location with the parameters
  response_location = rq.get(url_location, params=param_geo, headers=headers)
  if response_weather.status_code == 200 and response_location.status_code == 200:
    # Data for weather and location
    data_weather = response_weather.json()
    data_location = response_location.json()

    #Variable to get target city in API retunr in a object
    endereco = data_location.get("address", {})

    # Get the target city in object
    city = endereco.get("city") or endereco.get("town") or endereco.get("village")

    # Make table with weather and the target city
    df = makeTable(data_weather, city)
    dfs.append(df)

    # Show Table with all citys on:
    printTable()

  else:
    print("API ERROR...")

====== Daily city's weather ======
Type your latitude: 0
Type your longitude: 0
Do you wanna get information of another city? (Y/N)
> n

       city         day  temp_max  rain  wind
0  Campinas  2026-04-08      26.7   2.8  13.0
1  Campinas  2026-04-09      27.8   2.9  16.2
2  Campinas  2026-04-10      25.6   1.5  15.0
3  Campinas  2026-04-11      27.0   0.0  19.3
4  Campinas  2026-04-12      28.3   0.0  15.6
5  Campinas  2026-04-13      28.0   0.0   8.9
6  Campinas  2026-04-14      28.1   0.0  15.4
7  Campinas  2026-04-15      27.8   0.0  14.9

         city         day  temp_max  rain  wind
0  Indaiatuba  2026-04-08      27.5   6.4  16.8
1  Indaiatuba  2026-04-09      27.7   4.6  15.0
2  Indaiatuba  2026-04-10      24.9   0.0  13.3
3  Indaiatuba  2026-04-11      27.5   0.0  14.3
4  Indaiatuba  2026-04-12      28.5   0.0  10.0
5  Indaiatuba  2026-04-13      28.0   0.0   7.9
6  Indaiatuba  2026-04-14      28.3   0.0  13.8
7  Indaiatuba  2026-04-15      28.5   0.0  10.1

          city         day  temp_max  rain  wind
0  Hortolândia  2026-04-08      27.5   3.7  13.0
1  Hortolândia  2026-04-09      28.5   3.4  12.0
2  Hortolândia  2026-04-10      25.6   0.4  14.4
3  Hortolândia  2026-04-11      27.4   0.0  12.8
4  Hortolândia  2026-04-12      28.3   0.0  10.3
5  Hortolândia  2026-04-13      27.8   0.0   7.0
6  Hortolândia  2026-04-14      27.9   0.0   9.0
7  Hortolândia  2026-04-15      27.8   0.0   8.9

   city         day  temp_max  rain  wind
0   NaN  2026-04-08      28.6  18.3  12.9
1   NaN  2026-04-09      28.9   5.5  15.0
2   NaN  2026-04-10      28.9   5.6  10.7
3   NaN  2026-04-11      28.8   3.3  19.5
4   NaN  2026-04-12      28.7  11.9  14.1
5   NaN  2026-04-13      29.0   8.8  14.7
6   NaN  2026-04-14      28.6   8.2  17.8
7   NaN  2026-04-15      29.0   4.6  16.7